### ISSUE TITLE
Error upon first command

### ISSUE THREAD

**Issue by EmpathyHeals** [EmilJimenez21/VirtualShop#5] opened 2020-06-24 07:22 UTC
Your updates indicate you just finished adding basic command so maybe they didn't make it in my download, although I downloaded the plugin about 45 minutes ago. Anyway, first time I tried a command I got notified that an internal error occurred. Here are the logs from the plugin and my server. I like the concept for the plugin and I hope I can get to try it again soon. 

VirtualShop Log: https://pastebin.com/m9d9ct4w
My server log: https://pastebin.com/SZRdVFbv

Thanks! Emp

PS. I have a lot of plugins because we're in beta.

**Comment by EmilJimenez21** [comment] 2020-06-24 13:22
Hey @EmpathyHeals,

Thanks for reporting this bug, I have never tried to access the commands like that before /virtualshop:<command>. I will have to take a look and see what I can do to make this notation work. Thank you for reporting this error!

**Comment by chengts95** [comment] 2021-07-11 11:48
The command is not recognized as a SimpleCommad, which may be caused by the commands defined in plugin.yml.

**Comment by EmilJimenez21** [comment] 2023-05-23 20:30
Should be resolved in latest fix

**Closed as completed by EmilJimenez21** 2023-05-23 20:30 UTC
Labels: bug
