### ISSUE TITLE
Commands dont work.

### ISSUE THREAD

**Issue by DaDiGui** [EmilJimenez21/VirtualShop#10] opened 2020-12-04 19:31 UTC
- VS Log: https://pastebin.com/Nb9WCXfv
- Server Log: https://mclo.gs/33ZWW7F
- Custom Jar: CatServer-d35de0b-universal
- Forge: 1.12.2 v14.23.5.2854

**Comment by batman202012** [comment] 2021-01-18 08:46
I am also running into this issue with the exact same error on mohist forge+bukkit+spigot server 1.12.2 with Vault and essentials as an economy plugin. All commands except for the help command throw this error.
[error.log](https://github.com/EmilJimenez21/VirtualShop/files/5828887/error.log)

Edit: Error is caused by usage of com.bukkit.Sound.BLOCK_NOTE_BLOCK_BASS, forge changes this call

EDIT: fixed by turning off sounds in settings.yml however modded items do not sell correctly using /sell <amount> hand <price> because of meta data. Ex: all applied energistics 2 items show up as applied_energistics2_material

**Comment by EmilJimenez21** [comment] 2021-07-04 00:32
Updated the code to handle more versions using reflections.

**Closed as completed by EmilJimenez21** 2021-07-04 00:32 UTC
